### ISSUE TITLE
Crashing when killing an enemy

### ISSUE THREAD

**Issue by Etnewman** [ChanceToZoinks/internal-suffering-reborn#1]
**Describe the bug**

Good morning,

The bug in question is when I go to kill an enemy. The fighting portion works as intended, it is only when the enemy dies that the mod crashes. I am playing on iOS, and have several other mods installed. I will now paste the error logged.

*** ERROR START ***

An error occurred while processing ticks:
Active Action: melvorD:Combat
Error Name: TypeError
Error Message: undefined is not an object (evaluating 'this.enemy.monster')
Stack Trace:
@blob:https://ios.melvoridle.com/046489ed-a3fb-46af-be01-b6201365d081:1:6971
@https://ios.melvoridle.com/assets/js/built/mod.js?5027:831:56
onEnemyDeath@https://ios.melvoridle.com/assets/js/built/combatManager.js?5027:97:30
@https://ios.melvoridle.com/assets/js/built/mod.js?5027:829:33
checkDeath@https://ios.melvoridle.com/assets/js/built/baseManager.js?5027:26:84
tick@https://ios.melvoridle.com/assets/js/built/game.js?5027:167:158
runTicks@https://ios.melvoridle.com/assets/js/built/game.js?5027:164:100
processTime@https://ios.melvoridle.com/assets/js/built/game.js?5027:163:14
loop@https://ios.melvoridle.com/assets/js/built/game.js?5027:184:61
loop@[native code]
Current Equipment:

Action Information:
Is In Combat: true
Fight in Progress: true
-- Start of Player Information --
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: false
Standard Spell Selected: melvorD:WindStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
Active Prayers: None
Equipped Food:
-- End Player Information --
-- Start of Enemy Information --
Enemy: melvorD:Plant
Next Action: Attack
Next Attack: melvorD:Normal
Is Attacking: false
Standard Spell Selected: melvorD:WindStrike
Ancient Spell Selected undefined
Aurora Selected: undefined
Curse Selected: undefined
-- End Enemy Information --
Current Area Type: Combat
Current Area ID: melvorD:Farmlands
Modding Enabled. Loaded mods:
Dev
SEMI Core
Show Skill Modifiers
SEMI Drop Chances
SEMI Auto Farming
SEMI Auto Master
Shop Item Owned Indicator
Kills in Combat
SEMI Auto Bonfire
SEMI Auto Runecrafting
SEMI Auto Mine
Combat Indicators
SEMI Auto Smith Bars
SEMI Save on Close
AutoSort
Show Slayer Tier
ETA
Item Uses
Township Breakdown
Will I Die?
Bypass Agility Costs
Loot Chests
Mini Max Capes
Restore Speedruns
Chaos Returns
SEMI Auto Loot
Controlled Attack Style
SEMI Auto Eat
Internal Suffering Reborn
Combat Only Mode (HCCO / MCCO)
Combat Only Rebalance Beta Test

*** ERROR END ***

**To Reproduce**

1. Load a new character with internal suffering reborn selected (NOT HARDCORE)
2. Fight any NPC and defeat it.

**Expected behavior**

I expected the enemy to be defeated.

**Smartphone (please complete the following information):**

 - Device: iPhone 13 Pro
 - OS: iOS
 - Version: 16.2

Thanks!

E.N.

**Comment by ChanceToZoinks** [comment]
Thanks for the report. Fixed.
