### ISSUE TITLE
AFK progress let's players overflow level cap.

### ISSUE THREAD

**Issue by Etnewman** [ChanceToZoinks/internal-suffering-reborn#4]
**Describe the bug**

AFK Progress in a Skill allows the level cap to be breached. For instance, if I'm training woodcutting and close the app, I can train it over the level that the mod sets (the cap was 10 and I got it to 18)
It allows the player to, for instance, get benefits from astrology while breaching the level cap.

**To Reproduce**
1. Start training skill
2. Close app
3. Open app

**Expected behavior**

Skill to not level over cap

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS
 - Version: 16.2

**Additional context**

**Comment by ChanceToZoinks** [comment]
Hi, thanks for the report.
