### ISSUE TITLE
Levels on quick menu drop down showing 1/(level cap)

### ISSUE THREAD

**Issue by Etnewman** [ChanceToZoinks/internal-suffering-reborn#5]
**Describe the bug**

On the quick menu on the mobile app, all the levels are showing 1/(level cap).
I.E if the cap is 23, then showing 1/23. Shows golden 1/23 if the skill is maxed. The skill is actually the level it's supposed to be and shows when you click into the skill.

**To Reproduce**
1. Show quick menu on left side of screen.

**Expected behavior**

Levels to accurately reflect progress

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS
 - Version 16.2

**Additional context**

I really like this game mode, please let me know if I'm bugging (lol) the crap out of you with these bug issues and I won't submit another one!

**Comment by ChanceToZoinks** [comment]
~~Hi, thanks for the report. I can't replicate this on my iPhone--can you check what version of the mod you're running?~~
This should be fixed in the upcoming version.

And no worries you're not bothering me :) rather have more reports I can fix than none and people hating my mod.
