### ISSUE TITLE
Disabling a Skill while training it allows the player to continue training it.

### ISSUE THREAD

**Issue by Etnewman** [ChanceToZoinks/internal-suffering-reborn#6]
**Describe the bug**

When a player disables a skill while still training in that skill, they are still able to train in it until they switch skills. For example, if the player is fishing and disables it while fishing, they would still be able to fish whatever they were fishing until they switch off that skill.

**To Reproduce**
1. Begin training a skill
2. Disable the skill that you were training

**Expected behavior**

For the player to not be able to train the skill anymore immediately.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS
 - Version 16.2

**Additional context**

**Comment by ChanceToZoinks** [comment]
Hi, thanks for the report.
