### ISSUE TITLE
Agility rendering big crashes game

### ISSUE THREAD

**Issue by Etnewman** [ChanceToZoinks/internal-suffering-reborn#7]
**Describe the bug**

I was training cooking then disabled it to get to 49 total cap level. I had abused a bug earlier to let me build agility obstacles early. I think that may be why this bug is appearing. It happened when I tried to train it to the next unlock (level 40 from the previous cap of 36)

**To Reproduce**
1. Abuse current bug that allows offline progress to overflow level cap
2. Build agility obstacles past the current level cap
3. Disable a skill to raise the level cap
4. Train agility to the next milestone unlock level

**Expected behavior**

No crash to happen during rendering

**Screenshots**

**Stack Trace**

An error occurred while rendering:
Active Action: melvorD:Agility
Error Name: TypeError
Error Message: undefined is not an object (evaluating 'this.progressDivs[segmentNumber].bar')
Stack Trace:
startSegmentAnimation@https://ios.melvoridle.com/assets/js/built/agilityMenus.js?5027:50:200
animateFromTimer@https://ios.melvoridle.com/assets/js/built/agilityMenus.js?5027:59:27
renderProgressBar@https://ios.melvoridle.com/assets/js/built/agility.js?5027:166:174
render@https://ios.melvoridle.com/assets/js/built/agility.js?5027:136:161
@https://ios.melvoridle.com/assets/js/built/game.js?5027:170:69
forEach@[native code]
forEach@https://ios.melvoridle.com/assets/js/built/namespaceRegistry.js?5027:37:51
render@https://ios.melvoridle.com/assets/js/built/game.js?5027:170:46
loop@https://ios.melvoridle.com/assets/js/built/game.js?5027:186:41
loop@[native code]
Current Equipment:
Boots: melvorF:Boots_Of_Stealth
Amulet: melvorF:Jeweled_Necklace
Gloves: melvorF:Thieving_Gloves

Action Information:
Is Active: true

Active Obstacle Tier: 5
Built Obstacles (tier|obstacleID):
0:melvorF:RopeClimb
1:melvorF:BalanceBeam
2:melvorF:PitJump
3:melvorF:MudDive
4:melvorF:RooftopRun
5:melvorF:LakeSwim
Modding Enabled. Loaded mods:
Dev
SEMI Core
Show Skill Modifiers
SEMI Drop Chances
SEMI Auto Farming
SEMI Auto Master
Shop Item Owned Indicator
Kills in Combat
SEMI Auto Bonfire
SEMI Auto Runecrafting
SEMI Auto Mine
Combat Indicators
SEMI Auto Smith Bars
SEMI Save on Close
AutoSort
Show Slayer Tier
ETA
Item Uses
Township Breakdown
Will I Die?
Bypass Agility Costs
Loot Chests
Mini Max Capes
Restore Speedruns
Chaos Returns
SEMI Auto Loot
Controlled Attack Style
SEMI Auto Eat
Internal Suffering Reborn
Combat Only Mode (HCCO / MCCO)
Combat Only Rebalance Beta Test
SEMI Auto Bury

**End Stack Trace**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 
 - Version 16.2

**Additional context**

I'm not actually sure what the reason for this bug is. I also have the bypass agility mod installed and I am utilizing some of the bypass functions for that mod.

**Comment by Etnewman** [comment]
Note: I was able to resolve the issue by exporting and then importing the save into another slot. I'm not sure the reason behind this bug as it wasn't a crash (I was still training agility in the background) and importing the save seemed to fix it. It did say for android users to clear the apps cache, but iOS doesn't have that ability it seems.

**Comment by ChanceToZoinks** [comment]
Hi, thanks for the report.

It seems likely to me that the overflow bug you're describing interacted with bypass agility in some strange way. 

There is a pull request currently in progress to fix that overflow bug so I'm going to close this since the overflow should no longer be possible. If it occurs again please reopen this issue.

**Comment by Etnewman** [comment]
Hi! This bug is still occurring for me. It seems it happens when I switch to agility after not training it for a while. I've disabled the bypass agility mod. I'll throw the stack trace in from this morning. 

Just to note, I've disabled bypass agility and I still get this error. Thanks!

**Start Stack Trace**

An error occurred while rendering:
Active Action: melvorD:Agility
Error Name: TypeError
Error Message: undefined is not an object (evaluating 'this.progressDivs[segmentNumber].bar')
Stack Trace:
startSegmentAnimation@https://ios.melvoridle.com/assets/js/built/agilityMenus.js?5027:50:200
animateFromTimer@https://ios.melvoridle.com/assets/js/built/agilityMenus.js?5027:59:27
renderProgressBar@https://ios.melvoridle.com/assets/js/built/agility.js?5027:166:174
render@https://ios.melvoridle.com/assets/js/built/agility.js?5027:136:161
@https://ios.melvoridle.com/assets/js/built/game.js?5027:170:69
forEach@[native code]
forEach@https://ios.melvoridle.com/assets/js/built/namespaceRegistry.js?5027:37:51
render@https://ios.melvoridle.com/assets/js/built/game.js?5027:170:46
loop@https://ios.melvoridle.com/assets/js/built/game.js?5027:186:41
loop@[native code]
Current Equipment:
Helmet: melvorF:Golbin_Mask
Boots: melvorF:Boots_Of_Stealth
Amulet: melvorF:Jeweled_Necklace
Gloves: melvorF:Thieving_Gloves

Action Information:
Is Active: true

Active Obstacle Tier: 5
Built Obstacles (tier|obstacleID):
0:melvorF:RopeClimb
1:melvorF:BalanceBeam
2:melvorF:PitJump
3:melvorF:MudDive
4:melvorF:RooftopRun
5:melvorF:LakeSwim
Modding Enabled. Loaded mods:
Dev
SEMI Core
Show Skill Modifiers
SEMI Drop Chances
SEMI Auto Farming
SEMI Auto Master
Shop Item Owned Indicator
Kills in Combat
SEMI Auto Bonfire
SEMI Auto Runecrafting
SEMI Auto Mine
Combat Indicators
SEMI Auto Smith Bars
SEMI Save on Close
AutoSort
Show Slayer Tier
ETA
Item Uses
Township Breakdown
Will I Die?
Loot Chests
Mini Max Capes
Restore Speedruns
Chaos Returns
SEMI Auto Loot
Controlled Attack Style
SEMI Auto Eat
Internal Suffering Reborn
Combat Only Mode (HCCO / MCCO)
Combat Only Rebalance Beta Test
SEMI Auto Bury

**Stop Stack Trace**
